version: '3'
services:
  db:
    image: "postgres:13.1-alpine"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "wpd"
      POSTGRES_USER: "wpd"
      POSTGRES_DB: "wpd"
    volumes:
      - "./sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql"
      - "./sql/data.sql:/docker-entrypoint-initdb.d/02-data.sql"