spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wpd
    username: wpd
    password: wpd
  jpa:
    open-in-view: false
    database: POSTGRESQL
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        format_sql: false
logging:
  level:
    org.springframework.web: DEBUG
server:
  compression:
    enabled: true
  error:
    include-message: always